repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-xml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.12.1
  hooks:
  - id: stylua-system
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
