addon: Ferronnizer
deps:
  actions.lua:
  - toons/Kewhand-Westfall.lua
  - toons/Pixli-Westfall.lua
  - toons/Shydove-Westfall.lua
  - util.lua
  addonbox.lua:
  - util.lua
  bindings.lua:
  - util.lua
  buffs.lua:
  - buffdb.lua
  - util.lua
  chatframe.lua:
  - util.lua
  control.lua:
  - partychat.lua
  - util.lua
  drink.lua:
  - drinkdb.lua
  - fooddb.lua
  - util.lua
  minimap.lua:
  - util.lua
  mount.lua:
  - util.lua
  partychat.lua:
  - util.lua
  playerinfo.lua:
  - partychat.lua
  - util.lua
  save.lua:
  - util.lua
  tooltips.lua:
  - playerinfo.lua
  vars.lua:
  - util.lua
libs:
  chatthrottlelib: https://repos.curseforge.com/wow/chatthrottlelib/trunk
  libclassicspellactioncount: https://github.com/Ennea/LibClassicSpellActionCount-1.0.git
  libkeybound: https://repos.wowace.com/wow/libkeybound-1-0/trunk
  libactionbutton: https://repos.curseforge.com/wow/libactionbutton-1-0
  libclassicgearplanner: https://github.com/ferronn-dev/lib-classic-gear-planner.git
  libstub: https://repos.wowace.com/wow/libstub/trunk
roots:
- actions.lua
- addonbox.lua
- bindings.lua
- buffs.lua
- chatframe.lua
- control.lua
- drink.lua
- minimap.lua
- mount.lua
- save.lua
- tooltips.lua
- vars.lua
sql:
  buffdb.sql:
  - BuffDB
  fooddb.sql:
  - FoodDB
  drinkdb.sql:
  - DrinkDB
toc:
  Interface: 11306
  Title: Ferronnizer
  Notes: My personal WoW addon
