addon: Ferronnizer
deps:
  ace.lua:
  - libs/AceAddon-3.0/AceAddon-3.0.lua
  - libs/AceComm-3.0/AceComm-3.0.lua
  - libs/AceConsole-3.0/AceConsole-3.0.lua
  - libs/AceConfig-3.0/AceConfig-3.0.lua
  - libs/AceSerializer-3.0/AceSerializer-3.0.lua
  - ui.lua
  actions.lua:
  - bandagedb.lua
  - drinkdb.lua
  - fooddb.lua
  - galeshapley.lua
  - mountdb.lua
  - potiondb.lua
  - spelldb.lua
  - toons.lua
  - util.lua
  bindings.lua:
  - actions.lua
  - util.lua
  buffs.lua:
  - drinkdb.lua
  - fooddb.lua
  - spelldb.lua
  - util.lua
  carrot.lua:
  - util.lua
  chatframe.lua:
  - util.lua
  equip.lua:
  - datawatch.lua
  libs/AceComm-3.0/AceComm-3.0.lua:
  - libs/AceComm-3.0/ChatThrottleLib.lua
  - libs/CallbackHandler-1.0/CallbackHandler-1.0.lua
  libs/AceConfig-3.0/AceConfig-3.0.lua:
  - libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua
  - libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua
  - libs/AceConsole-3.0/AceConsole-3.0.lua
  libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:
  - libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua
  libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:
  - libs/CallbackHandler-1.0/CallbackHandler-1.0.lua
  minimap.lua:
  - util.lua
  nameplates.lua:
  - datawatch.lua
  - util.lua
  tooltips.lua:
  - util.lua
  toons.lua:
  - toons/TBC/Druid.lua
  - toons/TBC/Hunter.lua
  - toons/TBC/Mage.lua
  - toons/TBC/Paladin.lua
  - toons/TBC/Priest.lua
  - toons/TBC/Rogue.lua
  - toons/TBC/Shaman.lua
  - toons/TBC/Warlock.lua
  - toons/TBC/Warrior.lua
  - toons/Vanilla/Druid.lua
  - toons/Vanilla/Hunter.lua
  - toons/Vanilla/Mage.lua
  - toons/Vanilla/Paladin.lua
  - toons/Vanilla/Priest.lua
  - toons/Vanilla/Rogue.lua
  - toons/Vanilla/Shaman.lua
  - toons/Vanilla/Warlock.lua
  - toons/Vanilla/Warrior.lua
  toons/TBC/Druid.lua:
  - tooninit.lua
  toons/TBC/Hunter.lua:
  - tooninit.lua
  toons/TBC/Mage.lua:
  - tooninit.lua
  toons/TBC/Paladin.lua:
  - tooninit.lua
  toons/TBC/Priest.lua:
  - tooninit.lua
  toons/TBC/Rogue.lua:
  - tooninit.lua
  toons/TBC/Shaman.lua:
  - tooninit.lua
  toons/TBC/Warlock.lua:
  - tooninit.lua
  toons/TBC/Warrior.lua:
  - tooninit.lua
  toons/Vanilla/Druid.lua:
  - tooninit.lua
  toons/Vanilla/Hunter.lua:
  - tooninit.lua
  toons/Vanilla/Mage.lua:
  - tooninit.lua
  toons/Vanilla/Paladin.lua:
  - tooninit.lua
  toons/Vanilla/Priest.lua:
  - tooninit.lua
  toons/Vanilla/Rogue.lua:
  - tooninit.lua
  toons/Vanilla/Shaman.lua:
  - tooninit.lua
  toons/Vanilla/Warlock.lua:
  - tooninit.lua
  toons/Vanilla/Warrior.lua:
  - tooninit.lua
  ui.lua:
  - datawatch.lua
  - util.lua
  vars.lua:
  - util.lua
libs:
  AceAddon-3.0: https://repos.wowace.com/wow/ace3/trunk/AceAddon-3.0
  AceComm-3.0: https://repos.wowace.com/wow/ace3/trunk/AceComm-3.0
  AceConfig-3.0: https://repos.wowace.com/wow/ace3/trunk/AceConfig-3.0
  AceConsole-3.0: https://repos.wowace.com/wow/ace3/trunk/AceConsole-3.0
  AceSerializer-3.0: https://repos.wowace.com/wow/ace3/trunk/AceSerializer-3.0
  CallbackHandler-1.0:  https://repos.wowace.com/wow/callbackhandler/trunk/CallbackHandler-1.0
  LibStub: https://repos.wowace.com/wow/libstub/trunk
roots:
- ace.lua
- actions.lua
- bindings.lua
- buffs.lua
- carrot.lua
- chatframe.lua
- equip.lua
- minimap.lua
- nameplates.lua
- tooltips.lua
- ui.lua
- vars.lua
sql:
  bandagedb.sql:
  - BandageDB
  drinkdb.sql:
  - DrinkDB
  fooddb.sql:
  - FoodDB
  mountdb.sql:
  - MountGroundDB
  - MountFlightDB
  potiondb.sql:
  - HealthPotionDB
  - ManaPotionDB
  spelldb.sql:
  - SpellDB
toc:
  Title: Ferronnizer
  Notes: My personal WoW addon
versions:
- TBC
- Vanilla
