addon: Ferronnizer
deps:
  addonbox.lua:
  - util.lua
  bindings.lua:
  - util.lua
  buffs.lua:
  - buffdb.lua
  - util.lua
  chatframe.lua:
  - util.lua
  drink.lua:
  - util.lua
  minimap.lua:
  - util.lua
  mount.lua:
  - util.lua
  save.lua:
  - util.lua
  vars.lua:
  - util.lua
libs:
  libclassicgearplanner: https://github.com/ferronn-dev/lib-classic-gear-planner.git
  libstub: https://repos.wowace.com/wow/libstub/trunk
roots:
- addonbox.lua
- bindings.lua
- buffs.lua
- chatframe.lua
- drink.lua
- minimap.lua
- mount.lua
- save.lua
- vars.lua
sql:
  buffdb.sql:
  - BuffDB
toc:
  Interface: 11306
  Title: Ferronnizer
  Notes: My personal WoW addon
