addon: Ferronnizer
deps:
  actions.lua:
  - bandagedb.lua
  - drinkdb.lua
  - fooddb.lua
  - galeshapley.lua
  - mountdb.lua
  - potiondb.lua
  - spelldb.lua
  - toons.lua
  - util.lua
  bindings.lua:
  - actions.lua
  - util.lua
  buffs.lua:
  - drinkdb.lua
  - fooddb.lua
  - spelldb.lua
  - util.lua
  carrot.lua:
  - util.lua
  chatframe.lua:
  - util.lua
  minimap.lua:
  - util.lua
  save.lua:
  - util.lua
  toons.lua:
  - toons/TBC/Druid.lua
  - toons/TBC/Hunter.lua
  - toons/TBC/Mage.lua
  - toons/TBC/Paladin.lua
  - toons/TBC/Priest.lua
  - toons/TBC/Rogue.lua
  - toons/TBC/Shaman.lua
  - toons/TBC/Warlock.lua
  - toons/TBC/Warrior.lua
  - toons/Vanilla/Druid.lua
  - toons/Vanilla/Hunter.lua
  - toons/Vanilla/Mage.lua
  - toons/Vanilla/Paladin.lua
  - toons/Vanilla/Priest.lua
  - toons/Vanilla/Rogue.lua
  - toons/Vanilla/Shaman.lua
  - toons/Vanilla/Warlock.lua
  - toons/Vanilla/Warrior.lua
  toons/TBC/Druid.lua:
  - tooninit.lua
  toons/TBC/Hunter.lua:
  - tooninit.lua
  toons/TBC/Mage.lua:
  - tooninit.lua
  toons/TBC/Paladin.lua:
  - tooninit.lua
  toons/TBC/Priest.lua:
  - tooninit.lua
  toons/TBC/Rogue.lua:
  - tooninit.lua
  toons/TBC/Shaman.lua:
  - tooninit.lua
  toons/TBC/Warlock.lua:
  - tooninit.lua
  toons/TBC/Warrior.lua:
  - tooninit.lua
  toons/Vanilla/Druid.lua:
  - tooninit.lua
  toons/Vanilla/Hunter.lua:
  - tooninit.lua
  toons/Vanilla/Mage.lua:
  - tooninit.lua
  toons/Vanilla/Paladin.lua:
  - tooninit.lua
  toons/Vanilla/Priest.lua:
  - tooninit.lua
  toons/Vanilla/Rogue.lua:
  - tooninit.lua
  toons/Vanilla/Shaman.lua:
  - tooninit.lua
  toons/Vanilla/Warlock.lua:
  - tooninit.lua
  toons/Vanilla/Warrior.lua:
  - tooninit.lua
  vars.lua:
  - util.lua
libs:
  chatthrottlelib: https://repos.curseforge.com/wow/chatthrottlelib/trunk
  libkeybound: https://repos.wowace.com/wow/libkeybound-1-0/trunk
  libclassicgearplanner: https://github.com/ferronn-dev/LibClassicGearPlanner.git
  libstub: https://repos.wowace.com/wow/libstub/trunk
roots:
- actions.lua
- bindings.lua
- buffs.lua
- carrot.lua
- chatframe.lua
- minimap.lua
- save.lua
- tooltips.lua
- ui.xml
- vars.lua
sql:
  bandagedb.sql:
  - BandageDB
  drinkdb.sql:
  - DrinkDB
  fooddb.sql:
  - FoodDB
  mountdb.sql:
  - MountGroundDB
  - MountFlightDB
  potiondb.sql:
  - HealthPotionDB
  - ManaPotionDB
  spelldb.sql:
  - SpellDB
toc:
  Title: Ferronnizer
  Notes: My personal WoW addon
versions:
- BCC
- Classic
