addon: Ferronnizer
deps:
  addonbox.lua:
  - util.lua
  init.lua:
  - util.lua
  vars.lua:
  - util.lua
libs: {}
roots:
- addonbox.lua
- init.lua
- vars.lua
sql: {}
toc:
  Interface: 11306
  Title: Ferronnizer
  Notes: My personal WoW addon
