describe('save', function()
  it('does not crash through event sequence', function()
    wow.state:SendEvent('PLAYER_LOGIN')
    wow.state:SendEvent('PLAYER_ENTERING_WORLD')
    wow.state:SendEvent('PLAYER_LOGOUT')
  end)
end)
