describe('save', function()
  it('does not crash through event sequence', function()
    local state = require('addonloader')()
    state:SendEvent('PLAYER_LOGIN')
    state:SendEvent('PLAYER_ENTERING_WORLD')
    state:SendEvent('PLAYER_LOGOUT')
  end)
end)
