describe('vars', function()
  it('does nothing on addon load', function()
    local state = require('addonloader')()
    assert.same({}, state.cvars)
    assert.same(nil, state.consoleKey)
  end)
  it('performs changes on VARIABLES_LOADED', function()
    local state = require('addonloader')()
    state:SendEvent('VARIABLES_LOADED')
    assert.same(1, state.cvars.autoLootDefault)
    assert.same('F12', state.consoleKey)
  end)
end)
