describe('vars', function()
  it('does nothing on addon load', function()
    assert.same({}, wow.state.cvars)
    assert.same(nil, wow.state.consoleKey)
  end)
  it('performs changes on VARIABLES_LOADED', function()
    wow.state:SendEvent('VARIABLES_LOADED')
    assert.same(1, wow.state.cvars.autoLootDefault)
    assert.same('F12', wow.state.consoleKey)
  end)
end)
